"""Catalog contract: the canonical, source-of-truth metadata store.

The catalog tracks document identity, the immutable version timeline, parsed
chunks, and the *virtual* organization (sections + membership). It deliberately
does not store embeddings -- those live in the search index -- so the two layers
can scale and be swapped independently.
"""

from __future__ import annotations

from typing import List, Optional, Protocol

from ..models import Chunk, Document, Section, Version


class Catalog(Protocol):
    def init(self) -> None: ...

    # documents
    def upsert_document(self, doc: Document) -> None: ...
    def get_document(self, doc_id: str) -> Optional[Document]: ...
    def all_documents(self, include_deleted: bool = False) -> List[Document]: ...
    def mark_deleted(self, doc_id: str) -> None: ...

    # versions
    def upsert_version(self, version: Version) -> None: ...
    def get_current_version(self, doc_id: str) -> Optional[Version]: ...
    def get_version(self, doc_id: str, version_id: str) -> Optional[Version]: ...
    def set_version_flags(self, doc_id: str, version_id: str, **flags) -> None: ...

    # chunks
    def save_chunks(self, chunks: List[Chunk]) -> None: ...
    def get_chunks(self, doc_id: str, version_id: str) -> List[Chunk]: ...

    # sections (virtual organization)
    def upsert_section(self, section: Section) -> None: ...
    def all_sections(self) -> List[Section]: ...
    def assign_membership(
        self, doc_id: str, section_id: str, confidence: float = 1.0, rationale: str = ""
    ) -> None: ...
    def sections_for_doc(self, doc_id: str) -> List[str]: ...
    def docs_for_section(self, section_id: str) -> List[str]: ...

    def close(self) -> None: ...
